apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-express-username: dXNlcm5hbWU=
  mongo-express-password: cGFzc3dvcmQ=